default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: ci-sample
  username: frozenfung
  password:

test:
  <<: *default
  database: ci-sample 

production:
  <<: *default
  database: ci-sample
